### ISSUE TITLE
Cyrillic file name support

### ISSUE THREAD

**Issue by Artawower** [zen-fs/core#113]
Is there Cyrillic support? When I try to write a file with a Cyrillic name, I get an error

```
@zenfs_core.js?v=6a46cc40:12328 Uncaught SuppressedError: An error was suppressed during disposal.
    at new <anonymous> (@zenfs_core.js?v=6a46cc40:12328:11)
    at fail (@zenfs_core.js?v=6a46cc40:12307:34)
    at @zenfs_core.js?v=6a46cc40:12316:13
    at async Object.writeFile (@zenfs_core.js?v=6a46cc40:12761:7)
    at async main.js:18:1
```

Example: https://stackblitz.com/edit/vitejs-vite-hfhvwk?file=main.js

**Comment by james-pre** [comment]
@Artawower,

Thanks for submitting an issue. Could you please let me know what the suppressed error is? It's available via the `suppressed` property of `SuppressedError`. Thanks.

**Comment by Artawower** [comment]
```ts
await configure({
  mounts: {
    ['/']: InMemory,
  },
});

await fs.promises.writeFile('мой-файл.txt', 'HELLO!', 'utf-8');
```

```
_ErrnoError: ENOENT: No such file or directory, '/мой-файл.txt'
    at _ErrnoError.With (@zenfs_core.js?v=8b639b82:8389:12)
    at StoreFS._findINode (@zenfs_core.js?v=8b639b82:10899:24)
    at async StoreFS.sync (@zenfs_core.js?v=8b639b82:10759:27)
    at async PreloadFile.sync (@zenfs_core.js?v=8b639b82:10083:5)
    at async PreloadFile.write (@zenfs_core.js?v=8b639b82:10217:5)
    at async FileHandle.writeFile (@zenfs_core.js?v=8b639b82:12529:5)
    at async Object.writeFile (@zenfs_core.js?v=8b639b82:12754:5)
    at async main.js:20:3
  ```

**Comment by Artawower** [comment]
I don't know if this is important or not, but when I read all the files in a directory, I get a corrupted filename:

```ts
const files = await fs.promises.readdir('/');
console.log(files);
```

```
[
    "my-file.txt",
    "<>9-D09;.txt" // It supposed to be 'мой-файл.txt'
]
```

**Comment by james-pre** [comment]
Can you let me know if [1.0.6](https://github.com/zen-fs/core/releases/tag/v1.0.6) fixes it?

**Comment by Artawower** [comment]
Now everything works as expected. Thanks for the quick fix!

**Comment by james-pre** [comment]
Of course! I've also added a test to prevent any regression.
